config/routes.rb
Demo::Application.routes.draw do
  resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :website

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.paginate :per_page=>3, :page => params[:page], :conditions => ["name like ?", "%#{params[:search]}%"], :order => "name"
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to @company, :notice => "Successfully created company."
    else
      render :action => 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(params[:company])
      redirect_to @company, :notice  => "Successfully updated company."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_url, :notice => "Successfully destroyed company."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/companies/edit.html.erb
<% title "Edit Company" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @company %> |
  <%= link_to "View All", companies_path %>
</p>

app/views/companies/index.html.erb
<% title "Companies" %>

<%= form_tag companies_path, :method => :get %>
Search:
<%= text_field_tag "search", params[:search] %>
<%= submit_tag "Search" %>

<p>

<table width="50%">
  <tr>
    <th>Name</th>
    <th>Website</th>
  </tr>
  <% for company in @companies %>
    <tr>
      <td><%= link_to company.name, company %></td>
      <td><%= company.website %></td>
    </tr>
  <% end %>
</table>
<p>
    <%= will_paginate @companies %>
</p>
<p><%= link_to "New Company", new_company_path %></p>

app/views/companies/new.html.erb
<% title "New Company" %>

<%= render 'form' %>

<p><%= link_to "Back to List", companies_path %></p>

app/views/companies/show.html.erb
<% title "Company" %>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <%= link_to "Edit", edit_company_path(@company) %> |
  <%= link_to "Destroy", @company, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", companies_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>